DROP TABLE IF EXISTS `XCR_SCANPAYMENT_REGION_SET`;

CREATE TABLE `XCR_SCANPAYMENT_REGION_SET` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROVINCE_CODE` varchar(50) DEFAULT NULL COMMENT '省份ID',
  `PROVINCE_NAME` varchar(100) DEFAULT NULL COMMENT '省份名称',
  `IS_SHOW` tinyint(2) DEFAULT NULL COMMENT '是否显示0：不显示，1：显示',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

/*Data for the table `XCR_SCANPAYMENT_REGION_SET` */
insert  into `XCR_SCANPAYMENT_REGION_SET`
  (`ID`,`PROVINCE_CODE`,`PROVINCE_NAME`,`IS_SHOW`)
values
  (1,'320000','江苏',1),
  (2,'350000','福建',1),
  (3,'360000','江西',1),
  (4,'530000','云南',1),
  (5,'620000','甘肃',0),
  (6,'510000','四川',1),
  (7,'430000','湖南',1);
