ALTER TABLE XCR_BRANCHBANK_INFO ADD INDEX XCR_BRANCHBANK_INFO_INDEX_BANK_ID (bank_id) ;
ALTER TABLE XCR_SIGN_INFO ADD INDEX XCR_SIGN_INFO_INDEX_SHOP_CODE ( SHOP_CODE ) ;
ALTER TABLE XCR_SIGN_INFO ADD INDEX XCR_SIGN_INFO_INDEX_CREATE_TIME ( CREATE_TIME ) ;