
SELECT
	SUM(temp.SCORE) AS SCORE,
	temp.USER_ID AS MERCHANT_ID,
	temp.SHOP_CODE,
	MAX(temp.CREATE_TIME) AS CREATE_TIME,
	'SIGN' AS TYPE
FROM
	(
		SELECT
			SCORE,
			USER_ID,
			SHOP_CODE,
			CREATE_TIME
		FROM
			XCR_SIGN_INFO
		UNION ALL
			SELECT
				SCORE,
				USER_ID,
				SHOP_CODE,
				CREATE_TIME
			FROM
				XCR_SIGN_INFO_BACKUPS
	) temp
GROUP BY
	temp.SHOP_CODE
UNION ALL
	SELECT
		SUM(temp_mission.SCORE) AS SCORE,
		temp_mission.USER_ID AS MERCHANT_ID,
		temp_mission.MERCHANT_ID AS SHOP_CODE,
		temp_mission.CREATE_TIME AS CREATE_TIME,
		'MISSION' AS TYPE
	FROM
		(
			SELECT
				a.GRANT_NUM AS SCORE,
				h.MERCHANT_ID AS MERCHANT_ID,
				temp.FRANCHISEE_ID AS USER_ID,
				h.CREATE_TIME AS CREATE_TIME,
				i.MISSON_TEMPLATE_CODE AS TYPE
			FROM
				`XCR_MISSION_EXECUTE_HISTORY` h
			LEFT JOIN `XCR_MISSION_INFO` i ON h.MISSON_INFO_ID = i.ID
			LEFT JOIN `XCR_MISSION_AWARD` a ON a.`MISSON_INFO_ID` = h.MISSON_INFO_ID
			LEFT JOIN STORE temp ON temp.STORE_ID = h.MERCHANT_ID
			WHERE
				a.AWARD_TYPE = 'SCORE'
		) temp_mission
	GROUP BY
		temp_mission.MERCHANT_ID