DROP TABLE IF EXISTS XCR_MISSION_INFO;
CREATE TABLE XCR_MISSION_INFO
(
  ID  BIGINT AUTO_INCREMENT			COMMENT '主键',
  TRIGGER_INTERFACE_NAME  VARCHAR(100) 	COMMENT '触发接口名称',
  SPECIAL_AWARD_REMARK VARCHAR(200)		COMMENT '特殊奖励备注',
  BPM_IDENTITY  VARCHAR(40) 			COMMENT '奖励方法走流程时，对应工作流标示',
  RULE  TEXT		 					COMMENT '规则',
  CREATE_TIME  DATETIME 				COMMENT '创建时间',
  LINK VARCHAR(1000)					COMMENT '链接',
  NEED_MANUAL_AUDIT INT(1)				COMMENT '需要人工审核',
  STATUS  VARCHAR(40) 					COMMENT '状态',
  REASON  VARCHAR(100)					COMMENT '成为此状态的原因',
  TYPE  VARCHAR(40) 					COMMENT '类型（推荐、日常、学习）',
  MISSON_TEMPLATE_CODE VARCHAR(40)		COMMENT '任务模板编码',
  IS_DELETED INT(1)						COMMENT '是否删除',
  LAST_MODIFY_TIME DATETIME			COMMENT '最后修改时间',
  COMPLETE_TIPS	VARCHAR(200)			COMMENT '任务完成提示语',
  ICON_URL	VARCHAR(500)				COMMENT '任务图标的URL',
  NAME VARCHAR(40)						COMMENT '名称',
  DESCRIPTION VARCHAR(200)				COMMENT '描述说明',
  COURSE_ID VARCHAR(40)					COMMENT '课程id',
  SORT  INT		 						COMMENT '排序',
  IS_RELATED INT(1)						COMMENT '是否关联任务',  
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='任务信息表';

ALTER TABLE XCR_MISSION_INFO ADD INDEX XCR_MISSION_INFO_INDEX_STATUS ( STATUS ) ;

DROP TABLE IF EXISTS XCR_MISSION_AWARD;
CREATE TABLE XCR_MISSION_AWARD
(
  ID  BIGINT AUTO_INCREMENT				COMMENT '主键',
  MISSON_INFO_ID  BIGINT		 		COMMENT '任务信息ID',
  AWARD_TYPE  VARCHAR(40) 				COMMENT '奖励类型',
  GRANT_STYLE  VARCHAR(40)				COMMENT '奖励发放方式',
  GRANT_NUM  DOUBLE						COMMENT '奖励数量',  
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='任务奖励信息表';  

ALTER TABLE XCR_MISSION_AWARD ADD INDEX XCR_MISSION_AWARD_INDEX_MISSON_INFO_ID ( MISSON_INFO_ID ) ;

DROP TABLE IF EXISTS XCR_MISSION_EXECUTE_INFO;
CREATE TABLE XCR_MISSION_EXECUTE_INFO
(
  ID  	BIGINT AUTO_INCREMENT			COMMENT '主键',
  MISSON_INFO_ID  BIGINT				COMMENT '任务信息ID',
  SPECIAL_AWARD_REMARK VARCHAR(200)		COMMENT '特殊奖励备注',  
  MERCHANT_ID  VARCHAR(40) 				COMMENT '加盟商户ID',
  CREATE_TIME  DATETIME 				COMMENT '创建时间',
  STATUS  VARCHAR(40) 					COMMENT '状态',
  REASON  VARCHAR(100)					COMMENT '成为此状态的原因',
  TYPE  VARCHAR(40) 					COMMENT '类型',
  IS_DELETED INT(1)						COMMENT '是否删除',
  LAST_MODIFY_TIME DATETIME			COMMENT '最后修改时间',
  START_TIME	DATETIME				COMMENT '开始时间',
  END_TIME	DATETIME					COMMENT '结束时间',
  TRIGGER_INTERFACE_NAME  VARCHAR(100) 	COMMENT '触发接口名称',  
  COURSE_ID VARCHAR(40)					COMMENT '课程id',
  BPM_IDENTITY  VARCHAR(40) 			COMMENT '奖励方法走流程时，对应工作流标示',
  RULE  TEXT		 					COMMENT '规则',
  SORT  INT		 						COMMENT '排序',
  IS_BACKUP INT(1)						COMMENT '是否备份',
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='任务执行表';

ALTER TABLE XCR_MISSION_EXECUTE_INFO ADD INDEX XCR_MISSION_EXECUTE_INFO_INDEX_MISSON_INFO_ID ( MISSON_INFO_ID ) ;
ALTER TABLE XCR_MISSION_EXECUTE_INFO ADD INDEX XCR_MISSION_EXECUTE_INFO_INDEX_MERCHANT_ID ( MERCHANT_ID ) ;
ALTER TABLE XCR_MISSION_EXECUTE_INFO ADD INDEX XCR_MISSION_EXECUTE_INFO_INDEX_STATUS ( STATUS ) ;


DROP TABLE IF EXISTS XCR_MISSION_EXECUTE_AWARD;
CREATE TABLE XCR_MISSION_EXECUTE_AWARD
(
  ID  BIGINT AUTO_INCREMENT				COMMENT '主键',
  MISSON_EXECUTE_ID_INFO_ID  BIGINT		 		COMMENT '任务信息ID',
  AWARD_TYPE  VARCHAR(40) 				COMMENT '奖励类型',
  GRANT_STYLE  VARCHAR(40)				COMMENT '奖励发放方式',
  GRANT_NUM  DOUBLE						COMMENT '奖励数量',  
  GRANT_TIME  DATETIME		 			COMMENT '奖励发放时间',  
  GRANT_USER  VARCHAR(40) 				COMMENT '奖励发放人',
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='任务奖励执行表';  

ALTER TABLE XCR_MISSION_EXECUTE_AWARD ADD INDEX XCR_MISSION_EXECUTE_AWARD_INDEX_EXECUTE_ID ( MISSON_EXECUTE_ID_INFO_ID ) ;


DROP TABLE IF EXISTS XCR_MISSION_EXECUTE_HISTORY;
CREATE TABLE XCR_MISSION_EXECUTE_HISTORY
(
  ID  	BIGINT							COMMENT '主键',
  MISSON_INFO_ID  BIGINT				COMMENT '任务信息ID',
  SPECIAL_AWARD_REMARK VARCHAR(200)		COMMENT '特殊奖励备注',  
  MERCHANT_ID  VARCHAR(40) 				COMMENT '加盟商户ID',
  CREATE_TIME  DATETIME 				COMMENT '创建时间',
  STATUS  VARCHAR(40) 					COMMENT '状态',
  REASON  VARCHAR(100)					COMMENT '成为此状态的原因',
  TYPE  VARCHAR(40) 					COMMENT '类型',
  IS_DELETED INT(1)						COMMENT '是否删除',
  LAST_MODIFY_TIME DATETIME			COMMENT '最后修改时间',
  START_TIME	DATETIME				COMMENT '开始时间',
  END_TIME	DATETIME					COMMENT '结束时间',      
  TRIGGER_INTERFACE_NAME  VARCHAR(100) 	COMMENT '触发接口名称',  
  COURSE_ID VARCHAR(40)					COMMENT '课程id',
  BPM_IDENTITY  VARCHAR(40) 			COMMENT '奖励方法走流程时，对应工作流标示',
  RULE  TEXT		 					COMMENT '规则',
  SORT  INT		 						COMMENT '排序',
  IS_BACKUP INT(1)						COMMENT '是否备份',
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='任务执行历史表';

ALTER TABLE XCR_MISSION_EXECUTE_HISTORY ADD INDEX XCR_MISSION_EXECUTE_HISTORY_INDEX_MISSON_INFO_ID ( MISSON_INFO_ID ) ;
ALTER TABLE XCR_MISSION_EXECUTE_HISTORY ADD INDEX XCR_MISSION_EXECUTE_HISTORY_INDEX_MERCHANT_ID ( MERCHANT_ID ) ;
ALTER TABLE XCR_MISSION_EXECUTE_HISTORY ADD INDEX XCR_MISSION_EXECUTE_HISTORY_INDEX_STATUS ( STATUS ) ;


DROP TABLE IF EXISTS XCR_MISSION_EXECUTE_HISTORY_AWARD;
CREATE TABLE XCR_MISSION_EXECUTE_HISTORY_AWARD
(
  ID  BIGINT									COMMENT '主键',
  MISSON_EXECUTE_ID_INFO_ID  BIGINT		 		COMMENT '任务信息ID',
  AWARD_TYPE  VARCHAR(40) 				COMMENT '奖励类型',
  GRANT_STYLE  VARCHAR(40)				COMMENT '奖励发放方式',
  GRANT_NUM  DOUBLE						COMMENT '奖励数量',  
  GRANT_TIME  DATETIME		 			COMMENT '奖励发放时间',  
  GRANT_USER  VARCHAR(40) 				COMMENT '奖励发放人',
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='任务奖励执行历史表';  

ALTER TABLE XCR_MISSION_EXECUTE_HISTORY_AWARD ADD INDEX XCR_MISSION_EXECUTE_HISTORY_AWARD_INDEX_EXECUTE_ID ( MISSON_EXECUTE_ID_INFO_ID ) ;



DROP TABLE IF EXISTS XCR_MISSION_RELATED;
CREATE TABLE XCR_MISSION_RELATED
(
  ID  	BIGINT AUTO_INCREMENT				COMMENT '主键',
  MISSON_RELATED_NAME  VARCHAR(40) 			COMMENT '关联名称',
  MISSON_RELATED_DESCRIPTION  VARCHAR(200) 	COMMENT '关联描述',
  CREATE_TIME  DATETIME 					COMMENT '创建时间',
  STATUS  VARCHAR(40) 						COMMENT '状态',
  REASON  VARCHAR(100)						COMMENT '成为此状态的原因',
  TYPE  VARCHAR(40) 						COMMENT '类型',
  LAST_MODIFY_TIME DATETIME				COMMENT '最后修改时间',
    
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='任务关联表';

ALTER TABLE XCR_MISSION_RELATED ADD INDEX XCR_MISSION_RELATED_INDEX_STATUS( STATUS ) ;



DROP TABLE IF EXISTS XCR_MISSION_RELATED_DETAIL;
CREATE TABLE XCR_MISSION_RELATED_DETAIL
(
  ID  	BIGINT AUTO_INCREMENT				COMMENT '主键',
  MISSON_RELATED_ID  BIGINT 				COMMENT '任务关联表ID',
  MISSON_INFO_ID  BIGINT					COMMENT '任务信息表ID',
  LEVEL  INT 								COMMENT '级别',    
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='任务关联明细表';

ALTER TABLE XCR_MISSION_RELATED_DETAIL ADD INDEX XCR_MISSION_RELATED_DETAIL_INDEX_MISSON_RELATED_ID( MISSON_RELATED_ID ) ;

DROP TABLE IF EXISTS XCR_MISSION_TEMPLATE;
CREATE TABLE XCR_MISSION_TEMPLATE
(
  ID  	BIGINT AUTO_INCREMENT				COMMENT '主键',
  NAME VARCHAR(40) 							COMMENT '模板名称',
  SPECIAL_AWARD_REMARK VARCHAR(200)			COMMENT '特殊奖励备注',
  TYPE VARCHAR(40) 							COMMENT '模板类型',
  MISSION_TYPE	VARCHAR(40) 				COMMENT '任务类型',
  TEMPLATE_CODE  VARCHAR(40) 				COMMENT '模板编号',
  LINK  VARCHAR(1000)						COMMENT '连接',
  NEED_MANUAL_AUDIT  INT(1) 				COMMENT '是否要手工审核',    
  COMPLETE_TIPS VARCHAR(1000)				COMMENT '完成提示语',
  TRIGGER_INTERFACE_NAME VARCHAR(100)		COMMENT '触发接口名称',
  RULE_TEMPLATE TEXT						COMMENT '规则模板',
  IS_SCHEDULE INT(1) 						COMMENT '是否周期性任务',
  IS_DELETED INT(1) 						COMMENT '是否已删除',
  START_HOUR INT							COMMENT '几点开始',
  DURATION_HOURS	INT						COMMENT '持续几小时',
  SORT  INT		 						COMMENT '排序',
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='任务模板表';

ALTER TABLE XCR_MISSION_TEMPLATE ADD INDEX XCR_MISSION_TEMPLATE_INDEX_TEMPLATE_CODE( TEMPLATE_CODE ) ;


DROP TABLE IF EXISTS XCR_MISSION_ATTACHMENT;
CREATE TABLE XCR_MISSION_ATTACHMENT
(
  ID  	BIGINT AUTO_INCREMENT				COMMENT '主键',
  NAME VARCHAR(40) 							COMMENT '附件名称（枚举）',
  DESCRIPTION VARCHAR(200)					COMMENT '描述说明',
  ATTACHMENT_CODE VARCHAR(40)				COMMENT '附件编码（类型+任务ID+名称）',
  TYPE VARCHAR(40) 							COMMENT '附件类型（任务信息附件、任务过程附件）',
  MISSION_INFO_ID	VARCHAR(40) 			COMMENT '任务信息ID',
  MISSION_EXECUTE_ID  VARCHAR(40) 			COMMENT '任务执行ID',
  URL  VARCHAR(200)							COMMENT '附件地址',
  SORT  INT		 							COMMENT '排序',
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='任务附件表';

DROP TABLE IF EXISTS XCR_MISSION_ATTACHMENT_HISTORY;
CREATE TABLE XCR_MISSION_ATTACHMENT_HISTORY
(
  ID  	BIGINT 								COMMENT '主键',
  NAME VARCHAR(40) 							COMMENT '附件名称（枚举）',
  DESCRIPTION VARCHAR(200)					COMMENT '描述说明',
  ATTACHMENT_CODE VARCHAR(40)				COMMENT '附件编码（类型+任务ID+名称）',
  TYPE VARCHAR(40) 							COMMENT '附件类型（任务信息附件、任务过程附件）',
  MISSION_INFO_ID	VARCHAR(40) 			COMMENT '任务信息ID',
  MISSION_EXECUTE_ID  VARCHAR(40) 			COMMENT '任务执行ID',
  URL  VARCHAR(200)							COMMENT '附件地址',
  SORT  INT		 							COMMENT '排序',
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='任务附件历史表';

DROP TABLE IF EXISTS XCR_MISSION_OFFLINE_EXISTS_LIST;
CREATE TABLE XCR_MISSION_OFFLINE_EXISTS_LIST
(
  ID  BIGINT AUTO_INCREMENT					COMMENT '主键',
  NAME VARCHAR(40) 							COMMENT '名称',
  DESCRIPTION VARCHAR(200)					COMMENT '描述说明',
  MERCHANT_ID  VARCHAR(40)   				COMMENT '店铺编码',
  TEMPLATE_CODE VARCHAR(40)					COMMENT '任务模板编码',
  STATUS VARCHAR(40) 						COMMENT '任务状态',
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='门店线下已完成任务过滤表';


DROP TABLE IF EXISTS XCR_MISSION_BUY_LIST;
CREATE TABLE XCR_MISSION_BUY_LIST
(
  ID  BIGINT AUTO_INCREMENT					COMMENT '主键',
  LOGIN	 VARCHAR(40)   						COMMENT '用户登录名',						
  MISSION_ID  VARCHAR(40) 					COMMENT '任务ID',
  EXECUTE_ID  VARCHAR(40) 					COMMENT '可执行任务ID',
  ORDER_ID	VARCHAR(40) 					COMMENT '订单编号',
  PRODUCT_IDS	VARCHAR(40) 				COMMENT '商品编号',
  RETURN_VALUE	VARCHAR(1000) 				COMMENT '查询返回值',
  USED_PRODUCT_COUNT INT					COMMENT '使用的商品数量',
  PRODUCT_COUNT INT							COMMENT '总商品数量',
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='购买商品订单记录表';

DROP TABLE IF EXISTS XCR_MISSION_USER_HISTORY;
CREATE TABLE XCR_MISSION_USER_HISTORY
(
  ID  BIGINT AUTO_INCREMENT					COMMENT '主键',
  LOGIN	 VARCHAR(40)   						COMMENT '一账通登录名',						
  MERCHANT_ID  VARCHAR(40) 					COMMENT '门店编号',
  USER_NAME	VARCHAR(40) 					COMMENT '小超用户账号',
  REAL_NAME VARCHAR(40) 					COMMENT '真实姓名',
  LAST_MODIFY_TIME DATETIME				COMMENT '最后修改时间',
  COLUMN_ONE VARCHAR(40) 					COMMENT '手机app设备号',
  COLUMN_TWO VARCHAR(40) 					COMMENT '预留字段二',
  COLUMN_THREE VARCHAR(40) 					COMMENT '子公司id',
  SHOP_NAME VARCHAR(100) 					COMMENT '小超名称',
  UNIQUE KEY XCR_MISSION_USER_HISTORY_UNIQE_MERCHANT_ID (MERCHANT_ID),  
  PRIMARY KEY(ID)
)ENGINE=INNODB CHARSET=UTF8 COMMENT='任务用户历史表';